# Run all test, linters and other code checks before committing and pushing.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
      stages: [commit]
    - id: end-of-file-fixer
      stages: [commit]
    - id: check-yaml
      stages: [commit]
    - id: check-added-large-files
      stages: [commit]
  - repo: "local"
    hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      stages: [commit]
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      stages: [commit]
      # - id: pytest
      #   name: unit test
      #   entry: pytest --junitxml=reports/junit/junit.xml -v tests
      #   language: system
      #   types: [python]
      # - id: tests badge
      #   name: create-update tests badge
      #   entry: genbadge tests -o ./reports/junit/junit-badge.svg
      #   language: system
      #   types: [python]

    - id: coverage
      name: coverage
      entry: coverage run -m pytest -v tests
      language: system
      types: [python]
      stages: [commit]
    - id: coverage-report
      name: create coverage report
      entry: coverage report
      language: system
      types: [python]
      stages: [commit]
    # - id: report-html
    #   name: create coverage report html
    #   entry: coverage html
    #   language: system
    #   types: [python]
    #   stages: [push]
    # - id: report-xml
    #   name: create coverage report xml
    #   entry: coverage xml
    #   language: system
    #   types: [python]
    #   stages: [push]
    # - id: coverage badge
    #   name: create/update coverage badge
    #   entry: genbadge coverage -i ./reports/covxml/coverage.xml
    #   language: system
    #   types: [python]
    # - id: pip-compile
    #   name: compile requirements.txt
    #   entry: pip-compile
    #   language: system
    #   always_run: false
    #   files: requirements.in|setup.py$
    #   stages: [push]
