# Run all test, linters and other code checks before committing and pushing.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
  - repo: "local"
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
      - id: pytest
        name: unit test and coverage
        entry: coverage run -m pytest -v tests
        language: system
        types: [python]
      - id: coverage-report
        name: coverage report
        entry: coverage report -m
        language: system
        types: [python]
      - id: report-html
        name: coverage report html
        entry: coverage html
        language: system
        types: [python]
      - id: pip-compile
        name: compile requirements.txt
        entry: pip-compile
        language: system
        always_run: false
        files: requirements.in|setup.py$
        stages: [push]
