# Run all test, linters and other code checks before committing and pushing.
repos:
  - repo: "local"
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]


